spring.application.name=banking-test

# Enables the H2 console in browser
spring.h2.console.enabled=true

# Database Initialization
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# This to see debug logs
logging.level.com.fintech.banking_service=DEBUG

# Connection Settings
spring.datasource.url=jdbc:h2:file:./data/bankingdb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=